### ISSUE TITLE
Inconsistent units with astropy v4.0+

### ISSUE THREAD

**Issue by fkeruzore** [abeelen/nikamap#1]
[https://github.com/abeelen/nikamap/blob/master/nikamap/utils.py#L508](url)
`# Histogram remove the units so put it back here`
This is not true since astropy v4.0: [https://astropy.readthedocs.io/en/stable/changelog.html#id12](url).
Hence, putting it back means the quantity gets double units.

Example:
```
In [1]: import astropy

In [2]: astropy.__version__
Out[2]: '4.0.1.post1'

In [3]: from nikamap import NikaMap

In [4]: nm = NikaMap.read("map.fits", band="2mm")

In [5]: pk, k = nm.plot_PSD()
UnitConversionError: 'arcsec4 Jy4 / (beam2 deg4)' and 'Jy2 / sr' are not convertible
```

Solution: Removing L508 to 510.

This may have an impact at other points of the code too?

**Comment by abeelen** [comment]
Fixed by 40a615e16b843239e90ad48b6dbf6bc6aa5ed6b5 .Thanks @fkeruzore  ! I'll issue a new version to pypi
